"""Inline assets/icons.svg into every HTML page.

    python tools/inline_sprite.py

assets/icons.svg is the one place an icon is defined. Pages reference icons by
name with <use href="#name"/>, and this script copies the symbol definitions
into each page between the sprite markers.

Referencing the sprite as an external file would be smaller, since one file
would cache across every page. It does not survive being opened straight from
disk: browsers treat file:// URLs as unique origins and refuse the
cross-document reference, so the icons silently vanish during local preview.
Inlining costs a couple of KB per page and works everywhere.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPRITE = ROOT / "icons.svg"
PAGES = ["index.html", *(p.name and f"blog/{p.name}" for p in (ROOT / "blog").glob("*.html"))]

START = "    <!-- icon sprite: generated by tools/inline_sprite.py, do not hand-edit -->"
END = "    <!-- end icon sprite -->"


def sprite_markup() -> str:
    text = SPRITE.read_text(encoding="utf-8").strip()
    body = re.search(r"<svg[^>]*>(.*)</svg>", text, re.S).group(1).strip()
    inner = "\n".join("    " + line for line in body.splitlines())
    return (
        f'{START}\n'
        f'    <svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">\n'
        f"{inner}\n"
        f"    </svg>\n"
        f"{END}"
    )


def main() -> int:
    if not SPRITE.exists():
        print(f"missing {SPRITE}", file=sys.stderr)
        return 1

    markup = sprite_markup()
    block = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)

    for name in PAGES:
        path = ROOT / name
        if not path.exists():
            continue
        html = path.read_text(encoding="utf-8")

        if block.search(html):
            html = block.sub(markup, html)
        else:
            html = re.sub(r"(<body[^>]*>\n)", r"\1" + markup + "\n", html, count=1)

        # Pages reference the inlined symbols, not the file.
        html = re.sub(r'href="(?:\.\./)?assets/icons\.svg#', 'href="#', html)
        path.write_text(html, encoding="utf-8")
        print(f"{name}: {html.count('<use href=')} icon references")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
