"""
Inline the generated figures from assets/figures into the blog posts.

python tools/inline_figures.py

Figures are inlined rather than linked with <img> because an SVG loaded through <img> is an isolated document: 
it cannot see the page's CSS custom properties, so the figure would keep one fixed palette instead of following the theme.

The cost of inlining is that the copy in the HTML can drift from the generated file. 
This script removes that risk. 
Each figure sits behind a marker comment naming its spec, and this replaces the block underneath with whatever build_figures.py last produced.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIGURES = ROOT / "assets" / "figures"
POSTS = sorted((ROOT / "blog").glob("*.html"))

MARKER = re.compile(
    r"(?P<indent>[ \t]*)<!-- generated by tools/build_figures\.py from the "
    r"(?P<name>[\w-]+) spec -->\n"
    r"(?P<svg>(?:[ \t]*<div class=\"figure-scroll\">\n)?[ \t]*<svg\b.*?</svg>"
    r"(?:\n[ \t]*</div>)?)",
    re.S,
)


def main() -> int:
    if not FIGURES.is_dir():
        print(f"missing {FIGURES}", file=sys.stderr)
        return 1

    missing: list[str] = []
    for post in POSTS:
        html = post.read_text(encoding="utf-8")
        count = 0

        def swap(m: re.Match[str]) -> str:
            nonlocal count
            path = FIGURES / f"{m['name']}.svg"
            if not path.exists():
                missing.append(f"{post.name}: {m['name']}.svg")
                return m.group(0)
            indent = m["indent"]
            svg = path.read_text(encoding="utf-8").rstrip("\n")
            body = "\n".join(indent + line for line in svg.splitlines())
            count += 1
            inner = "\n".join("    " + line for line in body.splitlines())
            return (
                f"{indent}<!-- generated by tools/build_figures.py from the "
                f"{m['name']} spec -->\n"
                f'{indent}<div class="figure-scroll">\n{inner}\n{indent}</div>'
            )

        updated = MARKER.sub(swap, html)
        if updated != html:
            post.write_text(updated, encoding="utf-8")
        print(f"{post.relative_to(ROOT)}: {count} figure(s) refreshed")

    for m in missing:
        print(f"  missing figure {m}", file=sys.stderr)
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
